project:
  type: website
  output-dir: docs

website:
  title: "Jeff Raker.xyz"
  site-url: https://www.jeffraker.xyz
  description: "dérive: life adrift"
  navbar:
    background: "#000000"
    pinned: TRUE
    right:
      - text: "Blog"
        file: blog.qmd
      - icon: github
        href: https://github.com/
      - icon: rss
        href: blog.xml

format:
  html:
    theme: darkly
    css: styles.css

editor: visual

